import { DefaultTheme as RNDefaultTheme } from '@react-navigation/native';
import { Theme } from './types';

export const defaultTheme: Theme = {
  ...RNDefaultTheme,
  statusBarStyle: 'dark-content',
  fontFamily: {
    thin: 'Hellix-Thin',
    light: 'Hellix-Light',
    regular: 'Hellix-Regular',
    medium: 'Hellix-Medium',
    semibold: 'Hellix-SemiBold',
    bold: 'Hellix-Bold',
    extrabold: 'Hellix-ExtraBold',
    black: 'Hellix-Black',
    '100': 'Hellix-Thin',
    '300': 'Hellix-Light',
    '400': 'Hellix-Regular',
    '500': 'Hellix-Medium',
    '600': 'Hellix-SemiBold',
    '700': 'Hellix-Bold',
    '800': 'Hellix-ExtraBold',
    '900': 'Hellix-Black',
  },
  colors: {
    ...RNDefaultTheme.colors,
    brand: {
      primary: '#FF5A00',
      secondary: '#FFEADB',
      background1: '#FFFFFF',
      background2: '#FAFAFB',
      background3: '#E5E5E5',
    },
    dark: {
      dark1: '#D5D5DC',
      dark2: '#E2E2EA',
      dark3: '#F1F1F5',
      dark4: '#FAFAFB',
      dark5: '#FFFFFF',
      dark20: '#00000033',
    },
    grey: {
      grey1: '#171725',
      grey2: '#44444F',
      grey3: '#696974',
      grey4: '#92929D',
      grey5: '#B5B5BE',
      grey6: '#E6E8EC',
      grey7: '#E2E2EA',
      grey01: '#1717251a',
    },
    white: '#FFFFFF',
    black: '#000000',
    status: {
      green: {
        dark: '#82C43C',
        light: '#E6F3D8',
      },
      red: {
        dark: '#FC5A5A',
        light: '#FEDEDE',
      },
      yellow: {
        dark: '#FFC542',
        light: '#FFF2D3',
      },
      purple: {
        dark: '#A461D8',
        light: '#E4D0F3',
      },
      blue: {
        dark: '#0062FF',
        light: '#CCDFFF',
      },
      pink: {
        dark: '#FF9AD5',
        light: '#FFEBF7',
      },
      orange: {
        dark: '#FF5A00',
        light: '#FFEADB',
      },
      gold: {
        dark: '#FF8D00',
        light: '#FFAA55',
      },
    },
    primary: '#FF5A00',
    secondary: '#2D5FFC',
    background: '#FFFFFF',
    headerBackground: '#181A20',
    text: '#222B45',
    secondaryText: '#8F9BB3',
    disableText: '#BEC6D4',
    disableInput: '#F8F9FA',
    border: '#F1F1F5',
    success: '#82C43C',
    error: '#FC5A5A',
    disable: '#B5B5BE',
    divider: '#F1F1F5',
    tabActive: '#2D5EFD',
    tireColor: {
      platinum: '#7A7AB9',
      gold: '#DCC63D',
      star: '#DBAF60',
      silver: '#AEADAD',
    },
    error05: '#FC5A5A0D',
  },
};
